name             'graphite'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures graphite'
long_description 'Installs/Configures graphite'
version          '0.1.0'

depends 'apache2'
depends 'mysql'
depends 'database'
